### ISSUE TITLE
有没有istore内置的homebox内网测速的单独的AArch64的ipk插件包

### ISSUE THREAD

**Issue by x2287711259** [linkease/openwrt-app-actions#20]
有没有istore内置的homebox内网测速的单独的AArch64的ipk插件包

**Comment by jannson** [comment]
不是很 GET 到你的点？是这个？https://github.com/linkease/istore-packages/tree/main/homebox

还是这个？ https://istore.linkease.com/repo/aarch64_cortex-a53/nas/homebox_0.0.0-dev.2020062901-2_aarch64_cortex-a53.ipk

**Comment by x2287711259** [comment]
我要的是下边这个，谢谢
