### ISSUE TITLE
lib32gcc1安装失败。

### ISSUE THREAD

**Issue by mymine** [linkease/openwrt-app-actions#44]
lib32gcc1安装失败。
https://github.com/P3TERX/dotfiles/raw/master/.bashrc文件缺失。

**Comment by mymine** [comment]
> opkg install lib32gcc1 ? 不是 很理解，能说下上下文么？跟我们这个项目是啥关系？

actions在线编译报错:lib32gcc1安装失败。
然后https://github.com/P3TERX/dotfiles/raw/master/.bashrc文件缺失。

**Comment by jjm2473** [comment]
确实lib32gcc1安装失败，但是跟`https://github.com/P3TERX/dotfiles/raw/master/.bashrc`有啥关系

**Comment by jjm2473** [comment]
修好了

**Comment by mymine** [comment]
> 修好了

😂你把他删了，改成Ubuntu18.04镜像就可以了。
