### ISSUE TITLE
打不开，Istore安装完后打开如下

### ISSUE THREAD

**Issue by mimokini** [linkease/openwrt-app-actions#51]
No page is registered at '/admin/network/ap_modem'.
If this url belongs to an extension, make sure it is properly installed.
If the extension was recently installed, try removing the /tmp/luci-indexcache file.

清除完没有作用
rm -rf /tmp/luci-indexcache

**Comment by jjm2473** [comment]
ap_modem这个插件只支持openwrt 21以上的固件，也就是luci2.0以上，如果你的固件不是官方的，那就要问固件作者使用的luci版本了
