### ISSUE TITLE
Build failed: Process completed with exit code 2.

### ISSUE THREAD

**Issue by hillz2** [linkease/openwrt-app-actions#57]
I'm having this issue while building the IPKs

![2023-08-25-111330_1920x986_scrot](https://github.com/linkease/openwrt-app-actions/assets/25127225/927544a1-6357-4542-b22d-15019169476c)

Can you fix it ?

**Comment by hillz2** [comment]
I fixed that error above, but there's another error:

![2023-08-25-113029_1920x986_scrot](https://github.com/linkease/openwrt-app-actions/assets/25127225/21c86a70-d39f-4c29-936b-ace46b6f918a)

**Comment by jjm2473** [comment]
no, this github actions is not a complate compile enviroment, just use for compile luci-app-*

**Comment by jjm2473** [comment]
you can try 'only_luci' branch
