### ISSUE TITLE
蓝山云插件，在Nanopi R5S 下安装后重启Nanopi无法启动 无法进入openwrt web admin

### ISSUE THREAD

**Issue by crystalta** [linkease/openwrt-app-actions#59]
LuCI istoreos-22.03 branch (git-23.271.10849-b445bc4) / [ArgonTheme v2.2.10.8](https://github.com/jerrykuku/luci-theme-argon) / iStoreOS 22.03.5 2023092815
镜像ARM 64和ARM 6.4 2.2都无法成功启动都必须刷机
网心云无此问题

**Comment by jjm2473** [comment]
不明白你在说啥，你说的是什么插件有问题，还是固件有问题？

**Comment by crystalta** [comment]
不好意思 我是从蓝山云插件点进来的 是反馈蓝山云插件的问题，能告知一下作者是哪位吗 感谢您

**Comment by jjm2473** [comment]
插件那边应该有个官网按钮啊，你的插件更新到最新版本了吗
