### ISSUE TITLE
自编译固件，安装成功，但是无法打开web页面(ubuntu;kvm等)

### ISSUE THREAD

**Issue by Tao173** [linkease/openwrt-app-actions#69]
Error response from daemon: No such container: nextcloud
uci: Entry not found
把openwrt-app-actions/applications放到immortalwrt master源码编译之后，在服务里面安装插件可以正常安装，就是报错上面这一句，去docker看容器已经启动了，但是插件里面web+端口无法打开。

附带固件https://www.123pan.com/s/1tn9-mSMk3.html提取码:VIVH

**Comment by jjm2473** [comment]
用istoreos或者openwrt官方固件测试，其他固件自己研究。
